; exercise 4.41

; based on same flow as exercise 4.40

(define (multiple-dwelling)
  (define value '())
  (define (iter-fletcher f)
    (define (iter-cooper c)
      (define (iter-miller m)
        (define (iter-smith s)
          (define (iter-baker b)
            (if (not (or (= b 5)
                         (= b s)
                         (= b m)
                         (= b c)
                         (= b f)))
                (set! value (list (list 'baker b)
                  (list 'cooper c)
                  (list 'fletcher f)
                  (list 'miller m)
                  (list 'smith s))))
            (if (< b 5)
                (iter-baker (+ b 1))))
          (if (not (or (<= (abs (- s f)) 1)
                       (= s m)
                       (= s c)))
              (iter-baker 1))
          (if (< s 5)
              (iter-smith (+ s 1))))
        (if (not (or (<= m c)
                     (= m f)))
          (iter-smith 1))
        (if (< m 5)
            (iter-miller (+ m 1))))
      (if (not (or (= c 1)
                   (<= (abs (- f c)) 1)))
          (iter-miller 1))
      (if (< c 5)
          (iter-cooper (+ c 1))))
    (if (not (or (= f 1) (= f 5)))
        (iter-cooper 1))
    (if (< f 5)
        (iter-fletcher (+ f 1))))
  (iter-fletcher 1)
  value)

(multiple-dwelling)
;Value: ((baker 3) (cooper 2) (fletcher 4) (miller 5) (smith 1))